### ISSUE TITLE
Failed to set remote video description send parameters IPhone / Android

### ISSUE THREAD

**Issue by kaspars008** [Ankit-Aggarwal/SwiftyWebRTC#13]
Please help.
I published question here
https://stackoverflow.com/questions/52019677/failed-to-set-remote-video-description-send-parameters-iphone-android

**Comment by Ankit-Aggarwal** [comment]
As described in your question.
You are using `GoogleWebRTC ` framework so issue should be raised in there, i feel.. 
Closing this, since issue is not in `SwiftyWebRTC` implementation.
Hope you have already solved the issue or will get help soon.
